apiVersion: v1
kind: PersistentVolume
metadata:
  name: gitpv
  namespace: dev
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/f/git"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: devvc
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 20Gi
