apiVersion: traefik.io/v1alpha1
kind: IngressRouteTCP
metadata:
  name: ssh-dev-ingress
spec:
  entryPoints:
    - ssh
  routes:
    - kind: Rule
      match: Host(`dev`)
      services:
        - name: dev-service
          port: 22
